-- MySQL Script generated by MySQL Workbench
-- Thu Jul 28 15:50:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_projeto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_projeto_integrador` DEFAULT CHARACTER SET utf8 ;
USE `DB_projeto_integrador` ;

-- -----------------------------------------------------
-- Table `DB_projeto_integrador`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_projeto_integrador`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(225) NOT NULL,
  `login` VARCHAR(225) NOT NULL,
  `senha` VARCHAR(225) NOT NULL,
  `senha_admin` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_projeto_integrador`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_projeto_integrador`.`tb_tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ongs` VARCHAR(225) NOT NULL,
  `governo` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_projeto_integrador`.`tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_projeto_integrador`.`tb_postagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `subtitulo` VARCHAR(225) NULL,
  `autor` VARCHAR(225) NOT NULL,
  `conteudo` VARCHAR(1000) NOT NULL,
  `foto` VARCHAR(225) NULL,
  `tb_usuario_id` BIGINT NOT NULL,
  `tb_tema_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagens_tb_usuario_idx` (`tb_usuario_id` ASC) VISIBLE,
  INDEX `fk_tb_postagens_tb_tema1_idx` (`tb_tema_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagens_tb_usuario`
    FOREIGN KEY (`tb_usuario_id`)
    REFERENCES `DB_projeto_integrador`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagens_tb_tema1`
    FOREIGN KEY (`tb_tema_id`)
    REFERENCES `DB_projeto_integrador`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
